/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.EditoraDAO;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Editora;

/**
 *
 * @author prodrigo
 */
public class FormPesquisaEditora extends javax.swing.JInternalFrame {

    public FormPesquisaEditora() {
        initComponents();

        this.setTitle("Pesquisar Editora");
        this.setResizable(false);
        this.setIconifiable(false);
        this.setMaximizable(false);
        this.setClosable(true);
        configurarTabela();

        ButtonGroup bg = new ButtonGroup();
        bg.add(rdbId);
        bg.add(rdbNome);
        rdbNome.setSelected(true);
    }

    private void configurarTabela() {
        DefaultTableModel m = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        m.addColumn("Id");
        m.addColumn("Nome");
        m.addColumn("Cidade");
        tabResultado.setModel(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdbId = new javax.swing.JRadioButton();
        lblPesquisarPor = new javax.swing.JLabel();
        rdbNome = new javax.swing.JRadioButton();
        txtPesquisa = new javax.swing.JTextField();
        scpTabela = new javax.swing.JScrollPane();
        tabResultado = new javax.swing.JTable();
        btnListarPorId = new javax.swing.JButton();
        btnListarPorNome = new javax.swing.JButton();
        lblPesquisarPor1 = new javax.swing.JLabel();

        rdbId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rdbId.setText("Id");
        rdbId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbIdActionPerformed(evt);
            }
        });

        lblPesquisarPor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPesquisarPor.setText("Pesquisar por");

        rdbNome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rdbNome.setText("Nome");
        rdbNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbNomeActionPerformed(evt);
            }
        });

        txtPesquisa.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        tabResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabResultadoMouseClicked(evt);
            }
        });
        scpTabela.setViewportView(tabResultado);

        btnListarPorId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnListarPorId.setText("Id");
        btnListarPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarPorIdActionPerformed(evt);
            }
        });

        btnListarPorNome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnListarPorNome.setText("Nome");
        btnListarPorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarPorNomeActionPerformed(evt);
            }
        });

        lblPesquisarPor1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPesquisarPor1.setText("Listar por");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdbId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdbNome))
                            .addComponent(lblPesquisarPor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPesquisarPor1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnListarPorId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnListarPorNome))))
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scpTabela, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnListarPorId, btnListarPorNome});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPesquisarPor1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnListarPorNome)
                            .addComponent(btnListarPorId)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPesquisarPor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbNome)
                            .addComponent(rdbId))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbNomeActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtPesquisa.getText().isEmpty()) {
                JOptionPane.showMessageDialog(
                        null, "Informe o critério de pesquisa."
                );
            } else {
                configurarTabela();
                //
                // PESQUISAR POR ID
                //
                if (rdbId.isSelected()) {
                    try {
                        Editora e = new EditoraDAO().pesquisarPorId(
                                Integer.parseInt(txtPesquisa.getText())
                        );
                        if (e != null) {
                            DefaultTableModel m = (DefaultTableModel) tabResultado.getModel();
                            m.addRow(new Object[]{e.getId(), e.getNome(), e.getCidade()});
                            tabResultado.setModel(m);
                        } else {
                            JOptionPane.showMessageDialog(
                                    null, "Nenhum registro encontrado."
                            );
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(
                                null, "O campo de pesquisa deve ser numérico."
                        );
                    }
                } else {
                    //
                    // PESQUISAR POR NOME
                    //
                    List<Editora> lista = new EditoraDAO()
                            .pesquisarPorNome(txtPesquisa.getText());
                    if (lista.size() > 0) {
                        DefaultTableModel m = (DefaultTableModel) tabResultado.getModel();
                        for (Editora e : lista) {
                            m.addRow(new Object[]{e.getId(), e.getNome(), e.getCidade()});
                        }
                        tabResultado.setModel(m);
                    } else {
                        JOptionPane.showMessageDialog(
                                null, "Nenhum registro encontrado."
                        );
                    }
                }
            }
        }
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void tabResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabResultadoMouseClicked

        //CLIQUE DUPLO
        if (evt.getClickCount() == 2) {

            //Descobrir a linha selecionada
            int linha = tabResultado.getSelectedRow();

            //Recuperar o ID selecionado
            int id = Integer.parseInt(
                    tabResultado.getValueAt(linha, 0).toString()
            );

            //Abrir o FormCadastro
            FormCadastroEditora f
                    = new FormCadastroEditora(id);
            this.getDesktopPane().add(f);
            f.setVisible(true);

            //Fechar o FormPesquisa
            this.dispose();

        }

    }//GEN-LAST:event_tabResultadoMouseClicked

    private void btnListarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPorIdActionPerformed

        configurarTabela();
        List<Editora> lista = new EditoraDAO().listarPorId();
        if (lista.size() > 0) {
            DefaultTableModel m = (DefaultTableModel) 
                tabResultado.getModel();
            for (Editora e : lista) {
                m.addRow(new Object[]{e.getId(), e.getNome(), e.getCidade()});
            }
            tabResultado.setModel(m);
        } else {
            JOptionPane.showMessageDialog(
                    null, "Nenhum registro encontrado."
            );
        }

    }//GEN-LAST:event_btnListarPorIdActionPerformed

    private void btnListarPorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPorNomeActionPerformed

        configurarTabela();
        List<Editora> lista = new EditoraDAO().listarPorNome();
        if (lista.size() > 0) {
            DefaultTableModel m = (DefaultTableModel) 
                tabResultado.getModel();
            for (Editora e : lista) {
                m.addRow(new Object[]{e.getId(), e.getNome(), e.getCidade()});
            }
            tabResultado.setModel(m);
        } else {
            JOptionPane.showMessageDialog(
                    null, "Nenhum registro encontrado."
            );
        }
    }//GEN-LAST:event_btnListarPorNomeActionPerformed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void rdbIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbIdActionPerformed
    }//GEN-LAST:event_rdbIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListarPorId;
    private javax.swing.JButton btnListarPorNome;
    private javax.swing.JLabel lblPesquisarPor;
    private javax.swing.JLabel lblPesquisarPor1;
    private javax.swing.JRadioButton rdbId;
    private javax.swing.JRadioButton rdbNome;
    private javax.swing.JScrollPane scpTabela;
    private javax.swing.JTable tabResultado;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
